---
openapi: 3.0.0
info:
  title: FoneMe
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/NOMANNOOR87/FoneMe/1.0.0
  description: SwaggerHub API Auto Mocking
- url: https://zwilio.com/api/account/v1/
  description: SwaggerHub API Auto Mocking
paths:
  /phoneNumberToProfile:
    post:
      summary: Associates a phone number with a profile
      operationId: signup
      parameters:
      - name: Cnic
        in: query
        description: The user's CNIC
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Profile successfully associated with the phone number
        "400":
          description: Invalid CNIC or missing parameters
        "401":
          description: Unauthorized
        "409":
          description: Phone number already associated with another profile
        "500":
          description: Internal server error
      security:
      - bearerAuth: []
  /register:
    post:
      summary: Registers a new user with phone or email
      operationId: register
      parameters:
      - name: Name
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: FatherName
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: Cnic
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: PhoneNumber
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: CountryCode
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: NumberWithoutCode
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: Email
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "201":
          description: User registered successfully
        "400":
          description: Invalid data or missing parameters
        "409":
          description: User already exists
        "401":
          description: Unauthorized
        "500":
          description: Internal server error
      security:
      - bearerAuth: []
  /getsmscode:
    post:
      summary: Requests a code to be sent via SMS or email
      operationId: getCode
      parameters:
      - name: phone
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: email
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        "200":
          description: Code sent successfully
        "400":
          description: Invalid phone number or email
        "401":
          description: Unauthorized
        "429":
          description: Too many requests
        "500":
          description: Internal server error
      security:
      - bearerAuth: []
  /Signup2:
    post:
      summary: Completes signup using email after code verification
      operationId: signupWithEmail
      parameters:
      - name: email
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        "201":
          description: User signup completed successfully
        "400":
          description: Invalid email or missing code verification
        "401":
          description: Unauthorized
        "409":
          description: User already exists
        "500":
          description: Internal server error
      security:
      - bearerAuth: []
components:
  schemas: {}
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
